AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'spec/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'
    - 'lib/tasks/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
    - 'lib/tasks/*.rake'

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
