default: &default
  APPLICATION_HOST: 'http://localhost:3000'
  ASSET_HOST: 'http://localhost:3000'
  DEVISE_KEY: ''
  PORT: '3000'
  RACK_ENV: 'development'
  RAILS_MAX_THREADS: '3'
  SECRET_KEY_BASE: 'development_secret'
  SENTRY_DSN: ''
  SENTRY_ENVIRONMENT: 'development'
  SMTP_ADDRESS: ''
  SMTP_PASSWORD: ''
  SMTP_USERNAME: ''

test:
  <<: *default

development:
  <<: *default
