default: &default
  APPLICATION_HOST: 'http://localhost:3000'
  ASSET_HOST: 'http://localhost:3000'
  DEVISE_KEY: ''
  DIALOGFLOW_GREETING_EVENT: 'Welcome'
  GOOGLE_CLOUD_KEYFILE_JSON: >
    {}
  PORT: '3000'
  RACK_ENV: 'development'
  RAILS_MAX_THREADS: '3'
  SECRET_KEY_BASE: 'development_secret'
  SENTRY_DSN: ''
  SENTRY_ENVIRONMENT: 'development'
  SMTP_ADDRESS: ''
  SMTP_PASSWORD: ''
  SMTP_USERNAME: ''
  TWILIO_ACCOUNT_SID: ''
  TWILIO_AUTH_TOKEN: ''
  TWILIO_FROM_NUMBER: ''

test:
  <<: *default

development:
  <<: *default
