default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: banking_notifier_api_development

test:
  <<: *default
  database: banking_notifier_api_test

production:
  <<: *default
  database: banking_notifier_api_production
  username: banking_notifier_api
  password: <%= ENV['BANKING_NOTIFIER_API_DATABASE_PASSWORD'] %>
